sudo: required
language: go
go:
  - stable

notifications:
  email:
    recipients:
      - liuzoxan@gmail.com

services:
  - docker

env:
  - GO111MODULE=on

before_install:
  # for elastic search: https://www.elastic.co/guide/en/elasticsearch/reference/current/vm-max-map-count.html
  - sudo sysctl -w vm.max_map_count=262144
  - docker run -d -p 7777:9200 -e "discovery.type=single-node" --name elk docker.elastic.co/elasticsearch/elasticsearch:7.0.0
  - docker logs elk
  - docker inspect elk

script: go build
